src/helpers.R, src/retrieve_hbef.R, src/retrieve_lter.R, src/scrape_retrieval_template.R
made function for grabbing any data package from LTER, via PASTA API. harmonizing these will be another story...
=> lter data downloader g2g

src/generate_schema.sql, src/retrieval/retrieve_hbef.R
small fix needed in flag insertion; then can test grab data insertion; then can wire up shiny backend
=> db nearly filled out (including placeholders)

notes.txt
=> intro to git

data/general/site_data.csv, data/general/variables.csv, src/acquisition_master.R, src/global_helpers.R, src/helper_scrapyard.R, src/neon/neon/munge.R, src/neon/neon/processing_kernels.R, src/neon/network_helpers.R
=> improved error handling, readied neon mungers for development

src/lter/hbef/processing_kernels.R
@spencerrhea 
just a wee change
=> added ms_status column to hbef discharge

data/general/variables.csv, src/function_aliases.R, src/global_helpers.R, src/lter/hbef/domain_helpers.R, src/lter/hbef/munge.R, src/lter/hbef/processing_kernels.R, src/lter/hbef/retrieve.R, src/lter/network_helpers.R, src/neon/neon/munge.R, src/neon/neon/retrieve.R
=> hbef stream/precip chem progress

src/acquisition_master.R, src/dev_helpers.R, src/global_helpers.R, src/lter/hbef/domain_helpers.R, src/lter/hbef/munge.R, src/lter/hbef/processing_kernels.R, src/lter/hbef/products.csv, src/lter/hbef/retrieve.R, src/lter/network_helpers.R, src/neon/neon/munge.R, src/neon/neon/retrieve.R, src/neon/network_helpers.R
@spencerrhea 
@matthewross07 if interested
- first utilization of blacklist to avoid double retrieval of stream and precip chem (which are combined for hbef)
- new file for dev helpers (functions only useful during the development process)
- several harmonization measures; more on the way after this checkpoint
=> hbef precip and chem mungers fully integrated

src/acquisition_master.R, src/dev_helpers.R, src/function_aliases.R, src/global_helpers.R, src/lter/hbef/derive.R, src/lter/hbef/domain_helpers.R, src/lter/hbef/munge.R, src/lter/hbef/processing_kernels.R, src/lter/hbef/products.csv, src/lter/hbef/retrieve.R, src/lter/network_helpers.R, src/neon/neon/munge.R, src/neon/neon/processing_kernels.R, src/neon/neon/retrieve.R, src/neon/network_helpers.R
@spencerrhea
major remaining step: precip interp
along the way to that: ws delineation
=> rebuilding portal dataset the for-reals way. finishing up derive kernels

src/global/global_helpers.R
=> added recursive=TRUE to directory unlink (so it works now)

src/acquisition_master.R, src/global/global_helpers.R, src/lter/bonanza/products.csv, src/lter/hbef/products.csv, src/lter/santa_barbara/products.csv
@spencerrhea the last change made most domains process quickly enough, but HBEF was still a monster. So I made one more efficiency improvement, and now it's running like a dream. It doesn't always fully utilize all cores, because in some cases that would overload RAM. So in cases where there are a ton of timesteps, I just have it using half the cores instead. This process of trading off cores for RAM could be turned into a sliding scale, but it's still plenty fast even with half.
=> idw should finally be fully legit

src/acquisition_master.R, src/czo/network_helpers.R, src/global/general.R, src/global/global_helpers.R, src/lter/arctic/munge.R, src/lter/arctic/processing_kernels.R, src/lter/arctic/products.csv, src/lter/hbef/processing_kernels.R, src/lter/konza/products.csv, src/lter/network_helpers.R, src/neon/network_helpers.R
=> both flux functions improved; other little stuff

src/acquisition_master.R, src/czo/christina/derive.R, src/czo/christina/munge.R, src/czo/christina/processing_kernels.R, src/czo/christina/products.csv, src/czo/christina/retrieve.R, src/czo/network_helpers.R, src/lter/arctic/processing_kernels.R, src/lter/bonanza/processing_kernels.R, src/lter/hjandrews/processing_kernels.R, src/lter/konza/processing_kernels.R, src/lter/konza/products.csv, src/lter/luquillo/processing_kernels.R, src/neon/neon/products.csv
@vlahm this isn't time sensitive, as there are likely more fixes to come.
=> Discharge bug fixes

src/acquisition_master.R, src/global/global_helpers.R, src/lter/arctic/processing_kernels.R, src/lter/arctic/retrieve.R, src/lter/baltimore/derive.R, src/lter/bonanza/processing_kernels.R, src/lter/bonanza/products.csv, src/lter/bonanza/retrieve.R, src/lter/hjandrews/processing_kernels.R, src/lter/konza/processing_kernels.R, src/lter/luquillo/processing_kernels.R, src/lter/mcmurdo/domain_helpers.R, src/lter/mcmurdo/processing_kernels.R, src/lter/niwot/processing_kernels.R, src/lter/plum/domain_helpers.R, src/lter/plum/processing_kernels.R, src/lter/plum/products.csv, src/neon/neon/processing_kernels.R, src/neon/neon/retrieve.R, src/neon/network_helpers.R
@vlahm 
There are a lot of little things in here so no rush on merging. Some of the major things:
- Two changes to ms_read_raw_csv: In defining new column names (specifically suffixes) there was an instance where if alt_varflagcol_pattern and alt_datacol_pattern where null it was causing a vector with 2 extra position to be applied to the column names. This was causing the var flags order to be mixed and then would be applied to the wrong column when changing the column names of the data frame. Small change to fit it, and I don't think many domains were affected, McMurdo was where I saw it happening. Also added a option to define sampling type as I or G and overwrite identify sampling; in data that was irregular (due to only summer sampling or lots of data gaps, it was missis identifying …
=> Bugs hunted

src/global/global_helpers.R
=> pchem_only pathway through precip_pchem_pflux_idw

src/global/global_helpers.R
post-parallel conditionals for pchem_only scenario
=> double whoops

src/dev/delineation_burnstreams_test.R, src/global/global_helpers.R, src/global/munge_engines.R, src/neon/ancillary_scripts/neon_rating_curves.R
=> data.table summarizing in synchronize_timestep

src/acquisition_master.R, src/global/global_helpers.R, src/lter/network_helpers.R
@spencerrhea You're probably not working on any of these paths today, but just in case, here are some fixes and whatnots ^_^
=> catches, warnings, and some fixes

src/global/global_helpers.R
=> fixed handling of idw pchem-only case

src/acquisition_master.R, src/czo/network_helpers.R, src/doe/east_river/processing_kernels.R, src/lter/luquillo/munge.R, src/lter/luquillo/retrieve.R, src/lter/network_helpers.R, src/neon/neon/processing_kernels.R, src/neon/network_helpers.R
@vlahm nothing too big here, just these two things
=> product update warning email and small NEON fix

plots/diagnostic_plots.R, src/acquisition_master.R, src/dev/dev_helpers.R, src/dev/helper_scrapyard.R, src/dev/test/hbef_chem_and_q_coverage.R, src/dev/test/least_cost_breach_issue.R, src/global/global_helpers.R, src/lter/coweeta/processing_kernels.R, src/lter/plum/processing_kernels.R
@spencerrhea 
also: resultant shapefiles will never have holes now, and previous buffer radius is remembered between attempts
=> no longer using breach_depressions_least_cost

src/acquisition_master.R, src/czo/boulder/munge.R, src/czo/boulder/processing_kernels.R, src/czo/boulder/products.csv, src/czo/boulder/retrieve.R, src/dev/helper_scrapyard.R, src/doe/east_river/processing_kernels.R, src/doe/east_river/products.csv, src/global/general.R, src/global/general_kernels.R, src/global/global_helpers.R, src/lter/hbef/munge.R
=> general kernels and boulder update 

.gitignore, plots/diagnostic_plots.R, src/dev/highres_lowres_comparison.R, src/dev/test/konza_precip_issue.R, src/global/global_helpers.R, src/output_dataset_convenience_functions/load_entire_product.R
@spencerrhea these changes handle some edge cases in postprocessing that have caused bugs. `insert_gap_border_NAs` adds exactly two NAs to every data gap in portal/data--one at the beginning and one at the end of the gap--so that all gaps appear in time series visualization, but we don't have to carry around megabytes of NAs to fully fill every gap.
=> some postprocessing updates and fixes

src/acquisition_master.R, src/dev/dev_helpers.R, src/global/general.R, src/global/general_kernels.R, src/global/global_helpers.R, src/lter/luquillo/munge.R, src/lter/luquillo/processing_kernels.R
=> general kernels dynamic prefix 

src/global/global_helpers.R
moved portal/scheduled scripts to data_acquisition/src/global/global_helpers.R. they're now called from postprocess_entire_dataset
=> moved portal/scheduled_scripts

src/acquisition_master.R, src/global/global_helpers.R, src/lter/niwot/processing_kernels.R, src/lter/niwot/products.csv
=> niwot q update, watershed_summary update.

src/acquisition_master.R, src/usfs/tenderfoot/derive.R, src/usfs/tenderfoot/munge_versionless.R, src/usfs/tenderfoot/processing_kernels.R, src/usfs/tenderfoot/products.csv, src/usfs/tenderfoot/retrieve_versionless.R
Brought in tenderfoot ws data. @spencerrhea
=> second attempt at ingesting tenderfoot data to portal

ms_styleguide.md, src/usfs/tenderfoot/processing_kernels.R
=> just getting our local master branches synced up

src/acquisition_master.R, src/dev/dev_helpers.R, src/dev/functions_for_package.R, src/dev/site-data_shapefile_area_discrepancies.txt, src/global/general.R, src/global/general_kernels.R, src/global/global_helpers.R, src/usgs/usgs/munge.R
=> v1.0 alpha

src/acquisition_master.R, src/doe/east_river/processing_kernels.R, src/global/general.R, src/global/global_helpers.R, src/lter/luquillo/derive.R
Raster should not be used in the system anymore. Most switches were simple but a few of the function that were supposed to map from raster to terra required a few modification. @vlahm
=> raster to terra

src/acquisition_master.R, src/global/general.R, src/global/general_kernels.R, src/global/global_helpers.R, src/krycklan/krycklan/retrieve_versionless.R, src/lter/plum/processing_kernels.R, src/lter/plum/retrieve_versionless.R, src/neon/neon/retrieve_versionless.R, src/usfs/santee/processing_kernels.R, src/usfs/santee/retrieve_versionless.R, src/usfs/suef/retrieve_versionless.R, src/walker_branch/walker_branch/retrieve_versionless.R
New general products for snow and the camels things. The camels products for lithology, glhymps, daymet, and modis_igbp are all set to pending for now. Just because they are not all added to variables sheet and daymet is not fully complete. also changed sitename_NA to sitecode_NA @vlahm
=> New general products

src/acquisition_master.R, src/dev/check_negative_precip.R, src/global/global_helpers.R, src/usfs/suef/products.csv
@vlahm change to where we store data on drive. Now there is a manually_retrieved_data folder in the data folder that holds the domain data.
=> Gdrive folder structure change

src/acquisition_master.R, src/global/global_helpers.R
=> delineation improvements

data/general/site_data.csv, src/acquisition_master.R, src/bear/bear/processing_kernels.R, src/bear/bear/retrieve_versionless.R, src/czo/boulder/processing_kernels.R, src/czo/shale_hills/products.csv, src/dev/check_usgs_d_u_values.R, src/dev/get_site_numbers.R, src/global/global_helpers.R, src/lter/baltimore/processing_kernels.R, src/lter/hbef/munge.R, src/lter/luquillo/processing_kernels.R, src/lter/niwot/munge.R, src/lter/niwot/processing_kernels.R, src/lter/niwot/products.csv, src/lter/niwot/retrieve.R, src/lter/santa_barbara/processing_kernels.R, src/usgs/network_helpers.R
A few things here:
- Changed round_date to floor_date
- Changed populate_implicit_NAs to fill ms_status with NAs, not 0s, when called from synchronize_timestep so that ms_linear_interpolate will fill the ms_status with the status of the previous sample (was all 0 before)
- changed USGS Q Pulling to get the type of data (daily or unit) with the most days of data available
- added como site at Niwot
- Switch from evelope to emayili in email error function 
- Added a set_to_0 argument to ms_read_raw_csv. I don't know if we actually want this but I was starting to explore how to deal with detection limit flags in data columns. I am happy to keep working on this when I get back. 
@vlahm @westonslaughter
=> Few things before rebuild

src/global/global_helpers.R
=> granting 0 uncertainty for select variables

src/acquisition_master.R, src/global/global_helpers.R
=> detlim beast finally vanquished...?

src/acquisition_master.R, src/dev/dev_helpers.R, src/global/global_helpers.R
new dev func. can be called in `acq_master` to rebuild `portal/data` from `data_processing/data`. best used before running `postprocess_entire_dataset`!
=> rebuild_portal_data_before_postprocessing

src/acquisition_master.R, src/dev/spatial_check.R, src/global/global_helpers.R, src/lter/niwot/processing_kernels.R
When I added the como sites to niwot (they collected data there for ~20 years before it became a NEON site). I forgot to carry the changes through to derive. Should be updated now. 
@vlahm
=> Missed a Niwot update

src/acquisition_master.R, src/global/general.R, src/global/global_helpers.R
=> Camels reformat function 

src/acquisition_master.R, src/czo/network_helpers.R, src/dev/investigate_pchem_sample_regimes.R, src/dev/krycklan_stream_chem_investigate.R, src/global/global_helpers.R, src/krycklan/krycklan/processing_kernels.R, src/lter/hbef/processing_kernels.R, src/lter/hjandrews/processing_kernels.R, src/lter/konza/processing_kernels.R, src/lter/network_helpers.R, src/usfs/suef/processing_kernels.R
@westonslaughter just in case folk copy/paste from one of these modified kernels, let's get 'em into master
=> just some cleanup

src/webb/loch_vale/processing_kernels.R, src/webb/loch_vale/products.csv
=> will clean retrieval funcs

CHANGELOG.txt, notes.txt, src/dev/test/ms_read_raw_csv.R, src/global/global_helpers.R
=> ms_read_raw_csv update

src/global/global_helpers.R
self-merging because this is so wee
=> just a few phrases of documentation text

src/acquisition_master.R
@huo24 check Slack when you see this
=> synchronizing before purging large files from history
